GET http://localhost:3003/
content-type: application/json

###

POST http://localhost:3003/createUser
content-type: application/json

{
    "name": "User Teste",
    "email": "teste@email.com",
    "password": 123456
}
