GET http://localhost:3003/all
content-type: application/json

###

POST http://localhost:3003/createUser
content-type: application/json

{
    "name": "User Teste3",
    "email": "teste3@email.com",
    "password": 123456
}
