//Inseri um novo usuário na base de dados
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste8",
    "email": "emailteste8@email.com",
    "password": "23432535"
}

###

//Busca todos os usuários na base de dados
GET http://localhost:3003/user/user
Content-Type: application/json

###

//Inseri um novo filme na base de dados
POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "Filme Teste",
    "description": " Lorem ipsum dolor sit amet, consectetur",
    "durationInMinutes": 108,
    "yearOfRelease": 2023
}

###

//Buscar todos os filmes da base de dados
GET http://localhost:3003/movie/movie
Content-Type: application/json